### ISSUE TITLE
release checklist for v1.2

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#218]
- [x] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [x] (DEV) Create release candidate branch (branching, tagging) - Middleware and Frontend
- [x] (Business Owner) Identify destination & distribution targets (communications, announcements)
- [x] (SRE) Ensure SRE pipelines are in place
- [x] (DEV) unit & Integration tests have passed
- [x] (DEV) Create readme in git repo (scope closure)
- [x] (DEV) ensure changelog is in place
- [ ] (SRE) acceptance tests in a production environment has passed
- [x] (DEV) Documentation updates are in place (docs team)

**Comment by cspramit** [comment]
Jan to changelogs 3/10
No SRE acceptance tests needed 3/10
docs are essentially readme
versioning frontend and middleware to be in sync as and when per changes to the respective repos

**Comment by cspramit** [comment]
Is complete now
